version: "3.7"
services:
  mysqldb:
    image: "mysql"
    environment:
      MYSQL_DATABASE: grocerydb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - mysqldata:/var/lib/mysql

  api_service:
    image: assesstment/grocery:0.0.1
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb

volumes:
  mysqldata: